web:
  build: web
  ports:
    - "80:80"
  links:
    - db
    - queue
  volumes:
    - ./web:/usr/src/app
realtime:
  build: realtime
  ports:
    - "3000:3000"
  links:
    - queue
db:
  image: postgres
queue:
  image: rabbitmq
