web:
  build: ../web
  ports:
    - "80:80"
  links:
    - db
    - queue
  env_file: development.env
  volumes:
    - ../web:/app:ro
  command: python manage.py runserver 0.0.0.0:80
realtime:
  build: ../realtime
  ports:
    - "3000:3000"
  links:
    - queue
  env_file: development.env
db:
  image: postgres
  env_file: development.env
queue:
  image: rabbitmq
  env_file: development.env
