nginx:
  build: ../nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - web
    - realtime
  env_file: ./development.env
  volumes:
    - ../nginx:/app
web:
  build: ../web
  links:
    - db
    - queue
  env_file: ./development.env
  volumes:
    - ../web:/app
  command: python manage.py runserver 0.0.0.0:80
worker:
  build: ../web
  links:
    - db
    - queue
  env_file: ./development.env
  volumes:
    - ../web:/app
  command: worker
realtime:
  build: ../realtime
  links:
    - queue
  env_file: ./development.env
db:
  image: postgres
  env_file: ./development.env
queue:
  image: rabbitmq
  env_file: ./development.env
