nginx:
  build: ../nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - web
    - realtime
  env_file: ./production.env
web:
  build: ../web
  links:
    - db
    - queue
  env_file: ./production.env
worker:
  build: ../web
  links:
    - db
    - queue
  env_file: ./production.env
  command: celery -A project worker -l info
realtime:
  build: ../realtime
  links:
    - queue
  env_file: ./production.env
db:
  image: postgres
  env_file: ./production.env
queue:
  image: rabbitmq
  env_file: ./production.env
