web:
  build: ../web
  ports:
    - "80:80"
  links:
    - db
    - queue
  env_file: production.env
worker:
  build: ../web
  links:
    - db
    - queue
  env_file: production.env
  command: celery -A project worker -l info
realtime:
  build: ../realtime
  ports:
    - "3000:3000"
  links:
    - queue
  env_file: production.env
db:
  image: postgres
  env_file: production.env
queue:
  image: rabbitmq
  env_file: production.env
